# Your Name or Company
title: Guilherme Miotto

# Description of your website. This is used for social sharing.
description:  My mini personal webpage.

# A brief blurb about yourself
# content: I moved this to an include file (content.md)

# I moved the social links to _data

# General settings
url: https://gui-miotto.github.io/
baseurl: ""
markdown: kramdown
sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking  #TODO: see what this is

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
