- platform: linkedin
  url: https://www.linkedin.com/in/gui-miotto/
- platform: github
  url: https://github.com/gui-miotto
- platform: twitter
  url: https://twitter.com/gmiotto
- platform: cv papers
  url: https://gui-miotto.github.io/weekly_cv_takeaway/
